version: '3'

# Data volume for Mongo
volumes:
 mongostorage:

services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - mongostorage:/data/db
        ports:
          - 27017:27017
        networks:
          - back-end
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        restart: always


networks:
  front-end:
  back-end: